query ($postedAfterDate: DateTime!, $cursor: String) {
  posts(postedAfter: $postedAfterDate, after: $cursor, first: 20) {
    totalCount
    pageInfo {
      endCursor
      hasNextPage
    }
    edges {
      node {
        topics {
          edges {
            node {
              name
              id
            }
          }
        }
        id
        name
        description
        createdAt
        commentsCount
        reviewsCount
        reviewsRating
      }
    }
  }
}

{
	"postedAfterDate": "2020-11-22",
  "cursor": "MTA="
}